package com.beacon.wechat.api.model;

import java.io.Serializable;

public class WechatTemp implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -4814566067261863913L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopnc_wechat_temp.temp_id
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    private Integer tempId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopnc_wechat_temp.open_id
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopnc_wechat_temp.nickname
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopnc_wechat_temp.province
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopnc_wechat_temp.city
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopnc_wechat_temp.headimgurl
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    private String headimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopnc_wechat_temp.sex
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopnc_wechat_temp.time
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopnc_wechat_temp.lon
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    private String lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopnc_wechat_temp.lat
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    private String lat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopnc_wechat_temp.temp_id
     *
     * @return the value of shopnc_wechat_temp.temp_id
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public Integer getTempId() {
        return tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopnc_wechat_temp.temp_id
     *
     * @param tempId the value for shopnc_wechat_temp.temp_id
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public void setTempId(Integer tempId) {
        this.tempId = tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopnc_wechat_temp.open_id
     *
     * @return the value of shopnc_wechat_temp.open_id
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopnc_wechat_temp.open_id
     *
     * @param openId the value for shopnc_wechat_temp.open_id
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopnc_wechat_temp.nickname
     *
     * @return the value of shopnc_wechat_temp.nickname
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopnc_wechat_temp.nickname
     *
     * @param nickname the value for shopnc_wechat_temp.nickname
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopnc_wechat_temp.province
     *
     * @return the value of shopnc_wechat_temp.province
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopnc_wechat_temp.province
     *
     * @param province the value for shopnc_wechat_temp.province
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopnc_wechat_temp.city
     *
     * @return the value of shopnc_wechat_temp.city
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopnc_wechat_temp.city
     *
     * @param city the value for shopnc_wechat_temp.city
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopnc_wechat_temp.headimgurl
     *
     * @return the value of shopnc_wechat_temp.headimgurl
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopnc_wechat_temp.headimgurl
     *
     * @param headimgurl the value for shopnc_wechat_temp.headimgurl
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopnc_wechat_temp.sex
     *
     * @return the value of shopnc_wechat_temp.sex
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopnc_wechat_temp.sex
     *
     * @param sex the value for shopnc_wechat_temp.sex
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopnc_wechat_temp.time
     *
     * @return the value of shopnc_wechat_temp.time
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopnc_wechat_temp.time
     *
     * @param time the value for shopnc_wechat_temp.time
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopnc_wechat_temp.lon
     *
     * @return the value of shopnc_wechat_temp.lon
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public String getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopnc_wechat_temp.lon
     *
     * @param lon the value for shopnc_wechat_temp.lon
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public void setLon(String lon) {
        this.lon = lon == null ? null : lon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopnc_wechat_temp.lat
     *
     * @return the value of shopnc_wechat_temp.lat
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopnc_wechat_temp.lat
     *
     * @param lat the value for shopnc_wechat_temp.lat
     *
     * @mbggenerated Wed Feb 24 11:11:58 CST 2016
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }
}